# ==========================================
# SPEXRON ENGINE v2.0 - LOCALIZATION MODULE
# Tam TR/EN Dil Paketi - Purely Separated
# ==========================================

LOCALIZATION = {
    "tr": {
        "status_disconnected": "DURUM: BAĞLANTI KESİLDİ — Program seçilmedi",
        "status_connected": "BAĞLANDI: {} (PID: {})",
        "btn_select_process": "  Program Seç ",
        "btn_connected": "  Bağlı: {} (PID: {}) ",
        "lbl_status_game_detecting": "DURUM: Çalışan programlar taranıyor...",

        "lbl_found_addresses": "BULUNAN ADRESLER",
        "lbl_scanner": "TARAYICI",
        "lbl_cheat_table": "HİLE TABLOSU",
        "lbl_found_footer": "  ↑  Çift tıklatarak veya ⬇ butonuna basarak hile tablosuna ekleyin",
        "lbl_cheat_footer": "  ↑  Dondurmak için 'Aktif'e tıklayın  ·  Düzenlemek için çift tıklayın  ·  Sağ tıklayarak menüyü açın",

        "found_group_title": " Bulunan Adresler ",
        "tree_col_address": "Hex Adresi",
        "tree_col_value": "RAM Değeri",

        "scan_group_title": " Spexron Tarayıcı ",
        "lbl_search_val": "Aranacak Değer:",
        "lbl_scan_type": "Arama Tipi:",
        "lbl_val_type": "Değer Tipi:",

        "btn_first_scan": "İlk Tarama",
        "btn_next_scan": "Sonraki Tarama",
        "btn_reset": "Yeni Arama / Sıfırla",

        "scan_exact":     "Tam Eşleşme",
        "scan_bigger":    "Büyüktür",
        "scan_smaller":   "Küçüktür",
        "scan_between":   "Değer Aralığı",
        "scan_unknown":   "Bilinmeyen İlk Değer",
        "scan_increased": "Artan Değer",
        "scan_decreased": "Azalan Değer",
        "scan_changed":   "Değişen Değer",
        "scan_unchanged": "Değişmeyen Değer",

        "all_ram_scan": "[Tüm RAM Taranacak]",

        "cheat_table_title": " Aktif Hile Tablosu [ Çift tıkla → düzenle | Aktif sütun → dondur ] ",
        "tree_col_active":        "Aktif",
        "tree_col_description":   "Açıklama",
        "tree_col_saved_address": "Bellek Adresi",
        "tree_col_saved_type":    "Veri Tipi",
        "tree_col_saved_value":   "Değer",

        "tree_active_locked":   "  [X]  ",
        "tree_active_unlocked": "  [ ]  ",

        "log_idle":                 "DURUM: BOŞTA — Komut bekleniyor.",
        "log_awaiting":             "Program seçilmedi. Program Seç butonundan bir hedef seçin.",
        "log_hook_established":     "Program bağlantısı kuruldu: {} (PID: {}) — Yetki alındı.",
        "log_openprocess_failure":  "Bağlantı hatası: Program yetkisi alınamadı. Hata kodu: {}",
        "log_access_denied":        "Erişim Engellendi: Hedef program bağlı değil. Önce bir program seçin.",
        "log_specify_val":          "Uyarı: Taranacak değer belirtilmedi!",
        "log_scan_initiated":       "Taranıyor...",
        "log_scan_finished":        "Bellek taraması tamamlandı: {:.2f}s — {} adres bulundu.",
        "log_refining":             "Taranıyor...",
        "log_refined_finished":     "Adres uzayı daraltıldı. Eşleşen adres sayısı: {}",
        "log_reset":                "Arama parametreleri sıfırlandı. Bellek tabloları temizlendi.",
        "log_record_added":         "Hile tablosuna eklendi: {}",
        "log_records_added_multi":   "{} adet adres hile tablosuna toplu eklendi.",
        "log_records_deleted_multi": "{} adet hile kaydı tablodan silindi.",
        "log_records_frozen_multi":  "{} adet kayıt durumu güncellendi: {}",
        "log_freeze_active":        "Sabitleme aktif: {} adresi kilitlendi.",
        "log_writeprocessmemory":   "Bellek Yazma: {} adresine {} değeri yazıldı.",

        "lbl_dialog_addr":      "Adres:",
        "lbl_dialog_type":      "Veri Tipi:",
        "lbl_dialog_current":   "Mevcut Değer:",

        "val_1byte": "1 Bayt",
        "val_2bytes": "2 Bayt",
        "val_4bytes": "4 Bayt",
        "val_8bytes": "8 Bayt",
        "val_float": "Float",
        "val_double": "Double",
        "picker_lbl_count": "{} Program bulundu",

        "desc_default":         "Açıklama Yok",
        "desc_dialog_title":    "Açıklama Düzenle",
        "desc_dialog_prompt":   "Yeni bir açıklama girin:",
        "type_dialog_title":    "Veri Tipini Düzenle",
        "type_dialog_prompt":   "Veri tipini girin (1 Byte, 2 Bytes, 4 Bytes, 8 Bytes, Float, Double):",
        "val_dialog_title":     "Değeri Düzenle",
        "val_dialog_prompt":    "{} için yeni değer girin:",

        "picker_title":        "Program Seç — Spexron Engine",
        "picker_header":       "Bağlanılacak Program Seçin",
        "picker_filter":       "Filtre:",
        "picker_col_pid":      "Program ID (PID)",
        "picker_col_name":     "Program Adı",
        "picker_btn_refresh":  " Yenile ",
        "picker_btn_cancel":   " İptal ",
        "picker_btn_attach":   " Bağlan ",
        "picker_warning":      "Uyarı: Önce listeden bir program seçin!",

        "lang_label": "Dil:",
        "theme_light": "AYDINLIK",
        "theme_dark": "KARANLIK",

        # Context Menu
        "ctx_change_value":     "Değeri Değiştir",
        "ctx_set_value":        "Sabit Değer Yaz",
        "ctx_freeze":           "Aktif/Dondur",
        "ctx_unfreeze":         "Pasif Yap",
        "ctx_remove":           "Kayıttan Sil",
        "ctx_browse_memory":    "Bellek Bölgesine Git",
        "ctx_edit_desc":        "Açıklamayı Düzenle",
        "ctx_edit_type":        "Veri Tipini Değiştir",

        "set_val_title":    "Değer Yaz",
        "set_val_prompt":   "{} → Yeni değer girin:",

        # Found results count strings
        "lbl_results_zero": "  0 sonuç",
        "lbl_results_count": "  {} sonuç{}",
        "lbl_results_showing": "  ({} tanesi gösteriliyor - Toplam: {})",
        "lbl_entries_count": "  {} kayıt",

        # Add Manual strings
        "btn_add_manual": " + El ile Adres Ekle ",
        "btn_add_confirm": " Ekle ",
        "manual_dialog_title": "El ile Adres Ekle",
        "manual_dialog_prompt_addr": "Bellek Adresi (Hex):",
        "manual_dialog_prompt_desc": "Açıklama:",
        "manual_dialog_prompt_type": "Veri Tipi:",
        "manual_dialog_prompt_val": "Değer:",
        "manual_dialog_success": "El ile eklenen adres hile tablosuna eklendi: {}",
        "manual_dialog_err_invalid": "Hata: Geçersiz Hex adresi!",
        
        # Advanced Settings Dialog
        "btn_settings": "AYARLAR",
        "settings_dialog_title": "Gelişmiş Ayarlar",
        "settings_lbl_alignment": "Bellek Hizalama:",
        "settings_lbl_threads": "Arama İş Parçacığı Sayısı:",
        "settings_lbl_limit": "Maksimum Gösterilecek Sonuç:",
        "settings_btn_save": "✔ Kaydet",
        "settings_success": "Ayarlar başarıyla güncellendi.",
        "settings_lbl_theme": "Tema Seçimi:",
        "settings_lbl_freeze_rate": "Sabitleme Hızı:",
        "btn_about": "HAKKINDA",
        "settings_tab_general": "Genel",
        "settings_tab_appearance": "Görünüm",
        "settings_tab_about": "Hakkımda",

        # Pointer Scanner
        "ptr_title": "Gösterge Tarayıcı — Spexron Engine",
        "ptr_header": " GÖSTERGE VE OFFSET TARAYICI",
        "ptr_lbl_target": "Hedef Adres:",
        "ptr_lbl_max_offset": "Maksimum Offset:",
        "ptr_chk_static_only": " Sadece Statik Modülleri Filtrele",
        "ptr_btn_scan": "GÖSTERGE TARAMASINI BAŞLAT",
        "ptr_col_path": "GÖSTERGE YOLU",
        "ptr_col_offset": "OFFSET",
        "ptr_col_value": "DEĞER",
        "ptr_lbl_count": "{} gösterge yolu bulundu. (Çift tıklayarak tabloya ekleyin)",
        "ptr_log_added": "Hile tablosuna gösterge eklendi: {}",
        "ptr_err_no_process": "Hata: Önce bir program seçmelisiniz!",
        "ptr_err_invalid_addr": "Hata: Geçersiz hedef adresi!",

        # Gelişmiş Ayarlar (Cheat Engine Tarzı)
        "settings_tab_scan": "Tarama Ayarları",
        "settings_tab_hotkeys": "Kısayollar",
        "settings_tab_debugger": "Hata Ayıklayıcı",
        "settings_lbl_start_addr": "Başlangıç Adresi:",
        "settings_lbl_end_addr": "Bitiş Adresi:",
        "settings_lbl_mem_types": "Taranacak Bellek Tipleri:",
        "settings_lbl_mem_private": "Özel (Private - MEM_PRIVATE)",
        "settings_lbl_mem_image": "Resim (Image - MEM_IMAGE)",
        "settings_lbl_mem_mapped": "Eşlenmiş (Mapped - MEM_MAPPED)",
        "settings_lbl_writable": "Sadece Yazılabilir Bellek (Writable Only)",
        "settings_lbl_auto_attach": "Otomatik Bağlan (Auto-Attach):",
        "settings_lbl_auto_attach_proc": "Hedef Süreç Adı:",
        "settings_lbl_show_hex": "Değerleri Hexadecimal (On altılık) göster",
        "settings_lbl_show_status_bar": "Durum Çubuğunu Göster",
        "settings_lbl_update_rate": "Güncelleme Sıklığı:",
        "settings_lbl_hk_select_proc": "Program Seçme Kısayolu:",
        "settings_lbl_hk_pause_proc": "Süreç Duraklatma Kısayolu:",
        "settings_lbl_hk_freeze_addr": "Değer Sabitleme Kısayolu:",
        "settings_lbl_dbg_type": "Hata Ayıklayıcı Türü:",
        "settings_lbl_bp_type": "Kesme Noktası (Breakpoint) Türü:",
        "settings_tab_speedhack": "Speedhack Ayarları",
        "settings_lbl_confirm_close": "Programı kapatırken onay iste",
        "settings_lbl_protect_executable": "Yürütülebilir (Executable)",
        "settings_lbl_protect_copy_on_write": "Yazınca Kopyala (Copy on Write)",
        "settings_lbl_hk_speedhack": "Speedhack Kısayolu:",
        "settings_lbl_hk_next_scan": "Sonraki Arama Kısayolu:",
        "settings_lbl_hk_reset_scan": "Aramayı Sıfırlama Kısayolu:",
        "settings_lbl_sh_enable": "Speedhack'i Etkinleştir",
        "settings_lbl_sh_speed": "Speedhack Hızı:",
        "settings_lbl_dbg_hardware_type": "Donanımsal Kesme Koşulu:",
        "settings_confirm_close_title": "Çıkış Onayı",
        "settings_confirm_close_msg": "Spexron Engine programını kapatmak istediğinize emin misiniz?",
    },
    "en": {
        "status_disconnected": "STATUS: DISCONNECTED — No program selected",
        "status_connected": "CONNECTED: {} (PID: {})",
        "btn_select_process": "  Select Program ",
        "btn_connected": "  Attached: {} (PID: {}) ",
        "lbl_status_game_detecting": "STATUS: Enumerating running programs...",

        "lbl_found_addresses": "FOUND ADDRESSES",
        "lbl_scanner": "SCANNER",
        "lbl_cheat_table": "CHEAT TABLE",
        "lbl_found_footer": "  ↑  Double-click or press ⬇ to add to Cheat Table",
        "lbl_cheat_footer": "  ↑  Click 'Active' to freeze  ·  Double-click cell to edit  ·  Right-click for more options",

        "found_group_title": " Found Addresses ",
        "tree_col_address": "Hex Address",
        "tree_col_value": "RAM Value",

        "scan_group_title": " Spexron Scanner ",
        "lbl_search_val": "Search Value:",
        "lbl_scan_type": "Scan Type:",
        "lbl_val_type": "Value Type:",

        "btn_first_scan": "First Scan",
        "btn_next_scan": "Next Scan",
        "btn_reset": "New Scan / Reset",

        "scan_exact":     "Exact Value",
        "scan_bigger":    "Bigger Than",
        "scan_smaller":   "Smaller Than",
        "scan_between":   "Value Between",
        "scan_unknown":   "Unknown Initial Value",
        "scan_increased": "Increased Value",
        "scan_decreased": "Decreased Value",
        "scan_changed":   "Changed Value",
        "scan_unchanged": "Unchanged Value",

        "all_ram_scan": "[All RAM Will Be Scanned]",

        "cheat_table_title": " Active Cheat Table [ Double-click → edit | Active column → freeze ] ",
        "tree_col_active":        "Active",
        "tree_col_description":   "Description",
        "tree_col_saved_address": "Address",
        "tree_col_saved_type":    "Type",
        "tree_col_saved_value":   "Value",

        "tree_active_locked":   "  [X]  ",
        "tree_active_unlocked": "  [ ]  ",

        "log_idle":                "STATUS: IDLE — Awaiting instructions.",
        "log_awaiting":            "No program attached. Open Program Picker to select a target.",
        "log_hook_established":    "Program hook established: {} (PID: {}) — Access granted.",
        "log_openprocess_failure": "OpenProcess failure: Unable to acquire handle. Error: {}",
        "log_access_denied":       "Access Denied: No program attached. Please select a program first.",
        "log_specify_val":         "Warning: No target value specified for scan!",
        "log_scan_initiated":      "Scanning...",
        "log_scan_finished":       "Memory scan complete: {:.2f}s elapsed — {} addresses found.",
        "log_refining":            "Scanning...",
        "log_refined_finished":    "Address space refined. Matching allocations remaining: {}",
        "log_reset":               "Search parameters reset. Internal memory tables flushed.",
        "log_record_added":        "Record added to cheat table: {}",
        "log_records_added_multi":  "{} records bulk added to cheat table.",
        "log_records_deleted_multi": "{} cheat records deleted from table.",
        "log_records_frozen_multi":  "{} records status updated: {}",
        "log_freeze_active":       "Freeze loop active: Address {} is locked.",
        "log_writeprocessmemory":  "WriteProcessMemory: Address {} written with value {}.",

        "lbl_dialog_addr":      "Address:",
        "lbl_dialog_type":      "Type:",
        "lbl_dialog_current":   "Current:",

        "val_1byte": "1 Byte",
        "val_2bytes": "2 Bytes",
        "val_4bytes": "4 Bytes",
        "val_8bytes": "8 Bytes",
        "val_float": "Float",
        "val_double": "Double",
        "picker_lbl_count": "{} processes found",

        "desc_default":         "No description",
        "desc_dialog_title":    "Edit Description",
        "desc_dialog_prompt":   "Enter a new description:",
        "type_dialog_title":    "Edit Data Type",
        "type_dialog_prompt":   "Enter data type (1 Byte, 2 Bytes, 4 Bytes, 8 Bytes, Float, Double):",
        "val_dialog_title":     "Edit Value",
        "val_dialog_prompt":    "Enter new value for {}:",

        "picker_title":        "Select Program — Spexron Engine",
        "picker_header":       "Select Program to Attach",
        "picker_filter":       "Filter:",
        "picker_col_pid":      "Program ID (PID)",
        "picker_col_name":     "Program Name",
        "picker_btn_refresh":  " Refresh ",
        "picker_btn_cancel":   " Cancel ",
        "picker_btn_attach":   " Attach ",
        "picker_warning":      "Warning: Please select a program from the list first!",

        "lang_label": "Language:",
        "theme_light": "LIGHT",
        "theme_dark": "DARK",

        # Context Menu
        "ctx_change_value":     "Change Value",
        "ctx_set_value":        "Write Fixed Value",
        "ctx_freeze":           "Toggle Active",
        "ctx_unfreeze":         "Toggle Inactive",
        "ctx_remove":           "Remove from Table",
        "ctx_browse_memory":    "Browse Memory Region",
        "ctx_edit_desc":        "Edit Description",
        "ctx_edit_type":        "Change Data Type",

        "set_val_title":    "Write Value",
        "set_val_prompt":   "{} → Enter new value:",

        # Found results count strings
        "lbl_results_zero": "  0 results",
        "lbl_results_count": "  {} results{}",
        "lbl_results_showing": "  (showing {} of {})",
        "lbl_entries_count": "  {} entries",

        # Add Manual strings
        "btn_add_manual": " Add Address Manually ",
        "btn_add_confirm": " Add ",
        "manual_dialog_title": "Add Address Manually",
        "manual_dialog_prompt_addr": "Memory Address (Hex):",
        "manual_dialog_prompt_desc": "Description:",
        "manual_dialog_prompt_type": "Type:",
        "manual_dialog_prompt_val": "Value:",
        "manual_dialog_success": "Manual address added to cheat table: {}",
        "manual_dialog_err_invalid": "Error: Invalid Hex address!",
        
        # Advanced Settings Dialog
        "btn_settings": "SETTINGS",
        "settings_dialog_title": "Advanced Settings",
        "settings_lbl_alignment": "Memory Alignment:",
        "settings_lbl_threads": "Scanner Thread Count:",
        "settings_lbl_limit": "Max Displayed Results:",
        "settings_btn_save": "Save Settings",
        "settings_success": "Settings successfully updated.",
        "settings_lbl_theme": "Theme Selection:",
        "settings_lbl_freeze_rate": "Freeze Refresh Rate:",
        "btn_about": "ABOUT",
        "settings_tab_general": "General",
        "settings_tab_appearance": "Theme",
        "settings_tab_about": "About",

        # Pointer Scanner
        "ptr_title": "Pointer Scanner — Spexron Engine",
        "ptr_header": " POINTER AND OFFSET SCANNER",
        "ptr_lbl_target": "Target Address:",
        "ptr_lbl_max_offset": "Max Offset:",
        "ptr_chk_static_only": " Static Modules Only",
        "ptr_btn_scan": "START POINTER SCAN",
        "ptr_col_path": "POINTER PATH",
        "ptr_col_offset": "OFFSET",
        "ptr_col_value": "VALUE",
        "ptr_lbl_count": "{} pointer paths found. (Double-click to add to table)",
        "ptr_log_added": "Pointer path added to cheat table: {}",
        "ptr_err_no_process": "Error: You must select a program first!",
        "ptr_err_invalid_addr": "Error: Invalid target address!",

        # Advanced Settings (Cheat Engine Style)
        "settings_tab_scan": "Scan Settings",
        "settings_tab_hotkeys": "Hotkeys",
        "settings_tab_debugger": "Debugger Options",
        "settings_lbl_start_addr": "Start Address:",
        "settings_lbl_end_addr": "End Address:",
        "settings_lbl_mem_types": "Memory Scan Types:",
        "settings_lbl_mem_private": "Private (MEM_PRIVATE)",
        "settings_lbl_mem_image": "Image (MEM_IMAGE)",
        "settings_lbl_mem_mapped": "Mapped (MEM_MAPPED)",
        "settings_lbl_writable": "Writable memory only",
        "settings_lbl_auto_attach": "Auto-Attach to process:",
        "settings_lbl_auto_attach_proc": "Target Process Name:",
        "settings_lbl_show_hex": "Display values in hexadecimal format",
        "settings_lbl_show_status_bar": "Show status bar in main window",
        "settings_lbl_update_rate": "List Update Interval:",
        "settings_lbl_hk_select_proc": "Attach Process Hotkey:",
        "settings_lbl_hk_pause_proc": "Pause/Resume Hotkey:",
        "settings_lbl_hk_freeze_addr": "Freeze Value Hotkey:",
        "settings_lbl_dbg_type": "Debugger Type:",
        "settings_lbl_bp_type": "Breakpoint Method:",
        "settings_tab_speedhack": "Speedhack Settings",
        "settings_lbl_confirm_close": "Confirm before closing program",
        "settings_lbl_protect_executable": "Executable (PAGE_EXECUTE_READWRITE)",
        "settings_lbl_protect_copy_on_write": "Copy on Write (COW)",
        "settings_lbl_hk_speedhack": "Toggle Speedhack Hotkey:",
        "settings_lbl_hk_next_scan": "Next Scan Hotkey:",
        "settings_lbl_hk_reset_scan": "Reset Scan Hotkey:",
        "settings_lbl_sh_enable": "Enable Speedhack",
        "settings_lbl_sh_speed": "Speedhack Speed:",
        "settings_lbl_dbg_hardware_type": "Hardware Breakpoint Condition:",
        "settings_confirm_close_title": "Confirm Exit",
        "settings_confirm_close_msg": "Are you sure you want to close Spexron Engine?",
    }
}
